### ISSUE TITLE
Mapa mental Jesus Danery Lazo López 

### ISSUE THREAD

**Issue by Dasus2332** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Dasus2332#1]
[mapa mental Jesus Danery Lazo López.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-Dasus2332/files/9473756/mapa.mental.Jesus.Danery.Lazo.Lopez.pdf)

**Comment by josealfredo79** [comment]
Faltan algunos elementos

**Comment by josealfredo79** [comment]
Revisado...
